### ISSUE TITLE
Parallel feature is unsound

### ISSUE THREAD

**Issue by tgolsson** [jojolepro/world_dispatcher#1]
Hello! 

I noticed when playing around with planck_ecs that using the parallel feature here is unsound.

The problem is that World implements `unsafe Sync` manually, which implies that world is threadsafe even though its internal components are not. Unfortunately, allowing `get()` to be called from multiple threads simultaneously leads to acquiring multiple references from the RefCell, on different threads. As `RefCell` isn't Sync, this is unsound. Furthermore, this is a real bug as multiple systems dropping or acquiring the RefCell simultaneously can corrupt the reference counter. This prevents the Resource from ever being mutably borrowed again.

I'm not sure what solution would fit best with the principled design of this crate -- There's an [atomic_refcell](https://docs.rs/atomic_refcell/0.1.6/atomic_refcell/index.html) crate, and one could obviously use any flavour of `RwLock`. Neither solution is as elegant/succinct as the current one.

**Comment by AnneKitsune** [comment]
Oh wow, I didn't realize that RefCell wasn't Sync! Thanks for reporting this issue!
I tried quickly switching RefCell for RwLock, but the lack of an equivalent of `Ref::map` makes it not convenient.

I manually merged this patch https://github.com/bholley/atomic_refcell/pull/10/files for atomic_refcell into a fork https://github.com/jojolepro/atomic_refcell. I'll try contacting the maintainers of atomic_refcell, but if nothing happens I'll republish it with the patch shortly.

Thanks again!

**Comment by tgolsson** [comment]
That sounds good!

I did patch it locally using `parking_lot::RwLock` which has a mapping function, as I didn't notice that open PR for atomic_refcell. But the AtomicRefCell should be slightly more performant as the dispatcher upholds the other guarantees.

**Comment by AnneKitsune** [comment]
Assuming that atomic_refcell and the associated pull request that I merged are safe, this should be fixed as of world_dispatcher 1.1.0! :)
